### ISSUE TITLE
intro audio overlaps with popup cards

### ISSUE THREAD

**Issue by caseyyee** [EFForg/spot_the_surveillance#79]
I'm guessing the expected behavior here should be for the user to press "Get Started" before any of the hotspots are activated?

**Comment by lschatzkin** [comment]
Yes, except on mobile devices not using Cardboard.

**Comment by caseyyee** [comment]
So with mobile devices, the hotspots should be active right from the get-go?  Should the intro be canceled when user opens another popup?

Thanks for answering these questions, I have the audio working now, but just want to understand the desired behavior! :)

**Comment by lschatzkin** [comment]
Thanks for asking! 

1. Yes, on mobile the hotspots are active right away.
2.  Now that you bring it up, what would be best is if the Intro played immediately on mobile instead after a delay as it does now on the headset. The reason we have a delay on the intro audio is because when we demo it live, that's how much time it takes for us to hand off the headset to the  user and for them to put the headset on. 

If I remember correctly, the delay is in the audio itself, not a parameter, so that should be changed.

Also we've noticed that users (esp. first time) will move their head and accidentally "click" on something but still not have a coherent feeling of how to interact the experience -- because they didn't actually read the intro. The thought is if at least the narration is still going, they might actually get the information.

**Comment by cvan** [comment]
#85 was the approach I was thinking: show the menu but then close when a hotspot is found. I likely dupe reported the same issue you reported earlier here. Curious to hear what y'all think.

**Comment by lschatzkin** [comment]
Do you mean when you click on "Get Started" the card will remain until the first hotspot is found, instead of closing immediately?
